MVCTryAtWorkSchool/Models/Trainer.cs
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using System.Linq;
using System.Web;

namespace MVCTryAtWorkSchool.Models
{
    public class Trainer
    {
        
        public int TrainerID { get; set; }
        
        [Required]
        [Display(Name = "First Name")]
        [StringLength(50, ErrorMessage = "First name cannot be longer than 50 characters.")]
        public string FirstName { get; set; }

        [Required]
        [Display(Name = "Last Name")]
        [StringLength(50, ErrorMessage = "Last name cannot be longer than 50 characters.")]
        public string LastName { get; set; }

        [Required]
        [Display(Name ="Birth Date")]
        [DataType(DataType.Date)]
        [DisplayFormat(DataFormatString = "{0:yyyy-MM-dd}", ApplyFormatInEditMode = true)]
        public DateTime DateOfBirth { get; set; }
        public string Subject { get; set; }

        [Display(Name = "Courses")]
        public virtual ICollection<Course> Courses { get; set; }

        public virtual OfficeAssignment OfficeAssignment { get; set; }
    }
}

MVCTryAtWorkSchool/Controllers/TrainerController.cs
using System;
using System.Collections.Generic;
using System.Data;
using System.Data.Entity;
using System.Data.Entity.Infrastructure;
using System.Linq;
using System.Net;
using System.Web;
using System.Web.Mvc;
using MVCTryAtWorkSchool.DAL;
using MVCTryAtWorkSchool.Models;
using MVCTryAtWorkSchool.ViewModels;
using PagedList;


namespace MVCTryAtWorkSchool.Controllers
{
    public class TrainerController : Controller
    {
        private SchoolContext db = new SchoolContext();

        // GET: Trainer
        public ActionResult IndexWithoutViewBag(string sortOrder, string searchString, string currentFilter, int? page)
        {
            ViewBag.CurrentSort = sortOrder;
            ViewBag.FirstNameSortParm = string.IsNullOrEmpty(sortOrder) ? "name_desc" : "";
            ViewBag.LastNameSortParm = sortOrder == "Last" ? "last_desc" : "Last";
            ViewBag.DateSortParm = sortOrder == "Date" ? "date_desc" : "Date";
            ViewBag.SubjectSortParm = sortOrder == "Subject" ? "subj_desc" : "Subject";

            if (searchString != null)
            {
                page = 1;
            }
            else
            {
                searchString = currentFilter;
            }
            ViewBag.currentFilter = searchString;

            var trainers = from s in db.Trainers
                           select s;

            if (!String.IsNullOrEmpty(searchString))
            {
                trainers = trainers.Where(s => s.FirstName.Contains(searchString)
                                          || s.LastName.Contains(searchString)
                                         //|| s.DateOfBirth.ToString().Contains(searchString)
                                          || s.Subject.Contains(searchString)
                                         );
            }

            switch (sortOrder)
            {
                case "name_desc":
                    trainers = trainers.OrderByDescending(s => s.FirstName);
                    break;
                case "Last":
                    trainers = trainers.OrderBy(s => s.LastName);
                    break;
                case "last_desc":
                    trainers = trainers.OrderByDescending(s => s.LastName);
                    break;
                case "Date":
                    trainers = trainers.OrderBy(s => s.DateOfBirth);
                    break;
                case "date_desc":
                    trainers = trainers.OrderByDescending(s => s.DateOfBirth);
                    break;
                case "Subject":
                    trainers = trainers.OrderBy(s => s.Subject);
                    break;
                case "subj_desc":
                    trainers = trainers.OrderByDescending(s => s.Subject);
                    break;
                default:
                    trainers = trainers.OrderBy(s => s.FirstName);
                    break;
            }
            int pageSize = 3;
            int pageNumber = (page ?? 1);
            return View(trainers.ToPagedList(pageNumber, pageSize));
        }
        public ActionResult Index(int? id, int? courseID)
        {
            var viewModel = new TrainerIndexData();

            viewModel.Trainers = db.Trainers
                .Include(i => i.OfficeAssignment)
                .Include(i => i.Courses.Select(c => c.Department))
                .OrderBy(i => i.LastName);

            if (id != null)
            {
                ViewBag.TrainerID = id.Value;
                viewModel.Courses = viewModel.Trainers.Where(
                    i => i.TrainerID == id.Value).Single().Courses;
            }

            if (courseID != null)
            {
                ViewBag.CourseID = courseID.Value;
                // Lazy loading
                //viewModel.Enrollments = viewModel.Courses.Where(
                //    x => x.CourseID == courseID).Single().Enrollments;
                // Explicit loading
                var selectedCourse = viewModel.Courses.Where(x => x.CourseID == courseID).Single();
                db.Entry(selectedCourse).Collection(x => x.EnrollStudentCourses).Load();
                foreach (EnrollStudentCourse enrollment in selectedCourse.EnrollStudentCourses)
                {
                    db.Entry(enrollment).Reference(x => x.Student).Load();
                }

                viewModel.enrollStudentCourses = selectedCourse.EnrollStudentCourses;
            }

            return View(viewModel);
        }
        // GET: Trainer/Details/5
        public ActionResult Details(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            Trainer trainer = db.Trainers.Find(id);
            if (trainer == null)
            {
                return HttpNotFound();
            }
            return View(trainer);
        }

        // GET: Trainer/Create
        public ActionResult Create()
        {
            var trainer = new Trainer();
            trainer.Courses = new List<Course>();
            PopulateAssignedCourseData(trainer);
            return View();
        }

        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Create([Bind(Include = "FirstName,LastName,DateOfBirth,Subject,OfficeAssignment")]Trainer trainer, string[] selectedCourses)
        {
            if (selectedCourses != null)
            {
                trainer.Courses = new List<Course>();
                foreach (var course in selectedCourses)
                {
                    var courseToAdd = db.Courses.Find(int.Parse(course));
                    trainer.Courses.Add(courseToAdd);
                }
            }
            if (ModelState.IsValid)
            {
                db.Trainers.Add(trainer);
                db.SaveChanges();
                return RedirectToAction("Index");
            }
            PopulateAssignedCourseData(trainer);
            return View(trainer);
        }

        // GET: Trainer/Edit/5
        public ActionResult Edit(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            Trainer trainer = db.Trainers
                .Include(i => i.OfficeAssignment)
                .Include(i => i.Courses)
                .Where(i => i.TrainerID == id)
                .Single();
            PopulateAssignedCourseData(trainer);

            if (trainer == null)
            {
                return HttpNotFound();
            }
            return View(trainer);
        }
        private void PopulateAssignedCourseData(Trainer trainer)
        {
            var allCourses = db.Courses;
            var trainerCourses = new HashSet<int>(trainer.Courses.Select(c => c.CourseID));
            var viewModel = new List<AssignedCourseData>();
            foreach (var course in allCourses)
            {
                viewModel.Add(new AssignedCourseData
                {
                    CourseID = course.CourseID,
                    Title = course.Title,
                    Assigned = trainerCourses.Contains(course.CourseID)
                });
            }
            ViewBag.Courses = viewModel;
        }

        // POST: Trainer/Edit/5
        // To protect from overposting attacks, please enable the specific properties you want to bind to, for 
        // more details see https://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Edit(int? id, string[] selectedCourses)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            var trainerToUpdate = db.Trainers
                .Include(i => i.OfficeAssignment)
                .Include(i => i.Courses)
                .Where(i => i.TrainerID == id)
                .Single();

            if (TryUpdateModel(trainerToUpdate, "", new string[] { "FirstName", "LastName", "DateOfBirth", "Subject", "OfficeAssignment"}))
            {
                try
                {
                    if (String.IsNullOrWhiteSpace(trainerToUpdate.OfficeAssignment.Location))
                    {
                        trainerToUpdate.OfficeAssignment = null;
                    }

                    UpdateTrainerCourses(selectedCourses, trainerToUpdate);

                    db.SaveChanges();

                    return RedirectToAction("Index");
                }
                catch (RetryLimitExceededException)
                {
                    ModelState.AddModelError("", "Unable to save changes. Try again, and if the problem persists, see your system administrator.");
                }
            }
            PopulateAssignedCourseData(trainerToUpdate);
            return View(trainerToUpdate);
        }
        private void UpdateTrainerCourses(string[] selectedCourses,Trainer trainerToUpdate)
        {
            if(selectedCourses == null)
            {
                trainerToUpdate.Courses = new List<Course>();
                return;
            }

            var selectedCoursesHS = new HashSet<string>(selectedCourses);
            var trainerCourses = new HashSet<int>
                (trainerToUpdate.Courses.Select(c => c.CourseID));
           
            foreach(var course in db.Courses)
            {
                if(selectedCoursesHS.Contains(course.CourseID.ToString()))
                {
                    if (!trainerCourses.Contains(course.CourseID))
                    {
                        trainerToUpdate.Courses.Add(course);
                    }
                }
                else
                {
                    if (trainerCourses.Contains(course.CourseID))
                    {
                        trainerToUpdate.Courses.Remove(course);
                    }
                }
            }
        }

        // GET: Trainer/Delete/5

MVCTryAtWorkSchool/Views/Trainer/Create.cshtml
@model MVCTryAtWorkSchool.Models.Trainer

@{
    ViewBag.Title = "Create";
}

<h2>Create</h2>


@using (Html.BeginForm()) 
{
    @Html.AntiForgeryToken()
    
<div class="form-horizontal">
    <h4>Trainer</h4>
    <hr />
    @Html.ValidationSummary(true, "", new { @class = "text-danger" })
    <div class="form-group">
        @Html.LabelFor(model => model.FirstName, htmlAttributes: new { @class = "control-label col-md-2" })
        <div class="col-md-10">
            @Html.EditorFor(model => model.FirstName, new { htmlAttributes = new { @class = "form-control" } })
            @Html.ValidationMessageFor(model => model.FirstName, "", new { @class = "text-danger" })
        </div>
    </div>

    <div class="form-group">
        @Html.LabelFor(model => model.LastName, htmlAttributes: new { @class = "control-label col-md-2" })
        <div class="col-md-10">
            @Html.EditorFor(model => model.LastName, new { htmlAttributes = new { @class = "form-control" } })
            @Html.ValidationMessageFor(model => model.LastName, "", new { @class = "text-danger" })
        </div>
    </div>

    <div class="form-group">
        @Html.LabelFor(model => model.DateOfBirth, htmlAttributes: new { @class = "control-label col-md-2" })
        <div class="col-md-10">
            @Html.EditorFor(model => model.DateOfBirth, new { htmlAttributes = new { @class = "form-control" } })
            @Html.ValidationMessageFor(model => model.DateOfBirth, "", new { @class = "text-danger" })
        </div>
    </div>

    <div class="form-group">
        @Html.LabelFor(model => model.Subject, htmlAttributes: new { @class = "control-label col-md-2" })
        <div class="col-md-10">
            @Html.EditorFor(model => model.Subject, new { htmlAttributes = new { @class = "form-control" } })
            @Html.ValidationMessageFor(model => model.Subject, "", new { @class = "text-danger" })
        </div>
    </div>
    <div class="form-group">
        @Html.LabelFor(model => model.OfficeAssignment.Location, new { @class = "control-label col-md-2" })
        <div class="col-md-10">
            @Html.EditorFor(model => model.OfficeAssignment.Location)
            @Html.ValidationMessageFor(model => model.OfficeAssignment.Location)
        </div>
    </div>

    <div class="form-group">
        <div class="col-md-offset-2 col-md-10">
            <table>
                <tr>
                    @{
                        int cnt = 0;
                        List<MVCTryAtWorkSchool.ViewModels.AssignedCourseData> courses = ViewBag.Courses;

                        foreach (var course in courses)
                        {
                            if (cnt++ % 3 == 0)
                            {
                            @:</tr><tr>
                            }
                            @:<td>
                                <input type="checkbox"
                                       name="selectedCourses"
                                       value="@course.CourseID"
                                       @(Html.Raw(course.Assigned ? "checked=\"checked\"" : "")) />
                                @course.CourseID @:  @course.Title
                            @:</td>
                        }
                    @:</tr>
                    }
                </table>
            </div>
        </div>

        <div class="form-group">
            <div class="col-md-offset-2 col-md-10">
                <input type="submit" value="Create" class="btn btn-default" />
            </div>
        </div>
    </div>
}

<div>
    @Html.ActionLink("Back to List", "Index")
</div>

@section Scripts {
    @Scripts.Render("~/bundles/jqueryval")
}

MVCTryAtWorkSchool/Views/Trainer/Delete.cshtml
@model MVCTryAtWorkSchool.Models.Trainer

@{
    ViewBag.Title = "Delete";
}

<h2>Delete</h2>

<h3>Are you sure you want to delete this?</h3>
<div>
    <h4>Trainer</h4>
    <hr />
    <dl class="dl-horizontal">
        <dt>
            @Html.DisplayNameFor(model => model.FirstName)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.FirstName)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.LastName)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.LastName)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.DateOfBirth)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.DateOfBirth)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.Subject)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Subject)
        </dd>

    </dl>

    @using (Html.BeginForm()) {
        @Html.AntiForgeryToken()

        <div class="form-actions no-color">
            <input type="submit" value="Delete" class="btn btn-default" /> |
            @Html.ActionLink("Back to List", "Index")
        </div>
    }
</div>

MVCTryAtWorkSchool/Views/Trainer/Details.cshtml
@model MVCTryAtWorkSchool.Models.Trainer

@{
    ViewBag.Title = "Details";
}

<h2>Details</h2>

<div>
    <h4>Trainer</h4>
    <hr />
    <dl class="dl-horizontal">
        <dt>
            @Html.DisplayNameFor(model => model.FirstName)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.FirstName)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.LastName)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.LastName)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.DateOfBirth)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.DateOfBirth)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.Subject)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Subject)
        </dd>
        <dt>
            @Html.DisplayNameFor(model => model.OfficeAssignment)
        </dt>
        <dd>
            @Html.DisplayFor(model => model.OfficeAssignment)
        </dd>
    </dl>
</div>
<p>
    @Html.ActionLink("Edit", "Edit", new { id = Model.TrainerID }) |
    @Html.ActionLink("Back to List", "Index")
</p>

MVCTryAtWorkSchool/Views/Trainer/Edit.cshtml
@model MVCTryAtWorkSchool.Models.Trainer

@{
    ViewBag.Title = "Edit";
}

<h2>Edit</h2>


@using (Html.BeginForm())
{
    @Html.AntiForgeryToken()
    
<div class="form-horizontal">
    <h4>Trainer</h4>
    <hr />
    @Html.ValidationSummary(true, "", new { @class = "text-danger" })
    @Html.HiddenFor(model => model.TrainerID)

    <div class="form-group">
        @Html.LabelFor(model => model.FirstName, htmlAttributes: new { @class = "control-label col-md-2" })
        <div class="col-md-10">
            @Html.EditorFor(model => model.FirstName, new { htmlAttributes = new { @class = "form-control" } })
            @Html.ValidationMessageFor(model => model.FirstName, "", new { @class = "text-danger" })
        </div>
    </div>

    <div class="form-group">
        @Html.LabelFor(model => model.LastName, htmlAttributes: new { @class = "control-label col-md-2" })
        <div class="col-md-10">
            @Html.EditorFor(model => model.LastName, new { htmlAttributes = new { @class = "form-control" } })
            @Html.ValidationMessageFor(model => model.LastName, "", new { @class = "text-danger" })
        </div>
    </div>

    <div class="form-group">
        @Html.LabelFor(model => model.DateOfBirth, htmlAttributes: new { @class = "control-label col-md-2" })
        <div class="col-md-10">
            @Html.EditorFor(model => model.DateOfBirth, new { htmlAttributes = new { @class = "form-control" } })
            @Html.ValidationMessageFor(model => model.DateOfBirth, "", new { @class = "text-danger" })
        </div>
    </div>

    <div class="form-group">
        @Html.LabelFor(model => model.Subject, htmlAttributes: new { @class = "control-label col-md-2" })
        <div class="col-md-10">
            @Html.EditorFor(model => model.Subject, new { htmlAttributes = new { @class = "form-control" } })
            @Html.ValidationMessageFor(model => model.Subject, "", new { @class = "text-danger" })
        </div>
    </div>
    <div class="form-group">
        @Html.LabelFor(model => model.OfficeAssignment.Location, new { @class = "control-label col-md-2" })
        <div class="col-md-10">
            @Html.EditorFor(model => model.OfficeAssignment.Location)
            @Html.ValidationMessageFor(model => model.OfficeAssignment.Location)
        </div>
    </div>

    <div class="form-group">
        <div class="col-md-offset-2 col-md-10">
            <table>
                <tr>
                    @{
                        int cnt = 0;
                        List<MVCTryAtWorkSchool.ViewModels.AssignedCourseData> courses = ViewBag.Courses;

                        foreach (var course in courses)
                        {
                            if (cnt++ % 3 == 0)
                            {
                            @:</tr><tr>
                            }
                            @:<td>
                                <input type="checkbox"
                                       name="selectedCourses"
                                       value="@course.CourseID"
                                       @(Html.Raw(course.Assigned ? "checked=\"checked\"" : "")) />
                                @course.CourseID @:  @course.Title
                            @:</td>
                        }
                    @:</tr>
                    }
                </table>
            </div>
        </div>


        <div class="form-group">
            <div class="col-md-offset-2 col-md-10">
                <input type="submit" value="Save" class="btn btn-default" />
            </div>
        </div>
    </div>
}

<div>
    @Html.ActionLink("Back to List", "Index")
</div>

@section Scripts {
    @Scripts.Render("~/bundles/jqueryval")
}

MVCTryAtWorkSchool/Views/Trainer/Index.cshtml
@model MVCTryAtWorkSchool.ViewModels.TrainerIndexData
<link href="~/Content/PagedList.css" rel="stylesheet" type="text/css" />

@{
    ViewBag.Title = "Trainers";
}

<h2>Trainers</h2>

<p>
    @Html.ActionLink("Create New", "Create")
</p>
<table class="table">
    <tr>
        <th>
            First Name
        </th>
        <th>
            Last Name
        </th>
        <th>
            Birth Date
        </th>
        <th>
            Subject
        </th>
        <th>
            Office Location
        </th>
        <th>Courses</th>
    </tr>

    @foreach (var item in Model.Trainers)
    {
        string selectedRow = "";
        if (item.TrainerID == ViewBag.TrainerID)
        {
            selectedRow = "success";
        }
        <tr class="@selectedRow">
            <td>
                @Html.DisplayFor(modelItem => item.FirstName)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.LastName)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.DateOfBirth)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.Subject)
            </td>
            <td>
                @if (item.OfficeAssignment != null)
                {
                    @item.OfficeAssignment.Location
                }
            </td>
            <td>
                @{
                    foreach (var course in item.Courses)
                    {
                        @course.CourseID @:  @course.Title <br />
                    }
                }
            </td>
            <td>
                @Html.ActionLink("Select", "Index", new { id = item.TrainerID }) |
                @Html.ActionLink("Edit", "Edit", new { id = item.TrainerID }) |
                @Html.ActionLink("Details", "Details", new { id = item.TrainerID }) |
                @Html.ActionLink("Delete", "Delete", new { id = item.TrainerID })
            </td>
        </tr>
    }

</table>

@if (Model.Courses != null)
{
    <h3>Courses Taught by Selected Trainer</h3>
    <table class="table">
        <tr>
            <th>Number</th>
            <th>Title</th>
            <th>Stream</th>
            <th>Start Date</th>
            <th>End Date</th>
            <th>Department</th>
            <th></th>
        </tr>
        
        @foreach(var item in Model.Courses)
        {
            string selectedRow = "";
            if(item.CourseID == ViewBag.CourseID)
            {
                selectedRow = "success";
            }
            <tr class="@selectedRow">
                <td>
                    @item.CourseID
                </td>
                <td>
                    @item.Title
                </td>
                <td>
                     @item.Stream
                </td>
                <td>
                     @item.StartDate
                </td>
                <td>
                     @item.EndDate
                </td>
                <td>
                     @item.Department.Name
                </td>
                 <td>
                    @Html.ActionLink("Select","Index",new { courseID = item.CourseID})
                </td>
            </tr>
            
        }
    </table>
}
@if (Model.enrollStudentCourses != null)
{
    <h3>
        Students Enrolled in Selected Course
    </h3>
    <table class="table">
        <tr>
            <th>Name</th>
            <th>Grade</th>
        </tr>
        @foreach (var item in Model.enrollStudentCourses)
        {
            <tr>
                <td>
                    @item.Student.FullName
                </td>
                <td>
                    @Html.DisplayFor(modelitem => item.Grade)
                </td>
            </tr>
        }
    </table>
}

MVCTryAtWorkSchool/Views/Trainer/IndexWithoutViewModel.cshtml
@model PagedList.IPagedList<MVCTryAtWorkSchool.Models.Trainer>
@using PagedList.Mvc;
<link href="~/Content/PagedList.css" rel="stylesheet" type="text/css" />

@{
    ViewBag.Title = "Trainers";
}

<h2>Trainers</h2>

<p>
    @Html.ActionLink("Create New", "Create")
</p>
@using (Html.BeginForm("Index", "Trainer", FormMethod.Get))
{
    <p>
        Find: @Html.TextBox("SearchString", ViewBag.currentFilter as string)
        <input type="submit" value="Search" />
    </p>
}
<table class="table">
    <tr>
        <th>
            @Html.ActionLink("First Name", "Index", new { sortOrder = ViewBag.FirstNameSortParm, currentFilter = ViewBag.CurrentFilter })
        </th>
        <th>
            @Html.ActionLink("Last Name", "Index", new { sortOrder = ViewBag.LastNameSortParm, currentFilter = ViewBag.CurrentFilter })
        </th>
        <th>
            @Html.ActionLink("Date Of Birth", "Index", new { sortOrder = ViewBag.DateSortParm, currentFilter = ViewBag.CurrentFilter })
        </th>
        <th>
            @Html.ActionLink("Subject", "Index", new { sortOrder = ViewBag.SubjectSortParm, currentFilter = ViewBag.CurrentFilter })
        </th>
    </tr>

    @foreach (var item in Model)
    {
        <tr>
            <td>
                @Html.DisplayFor(modelItem => item.FirstName)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.LastName)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.DateOfBirth)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.Subject)
            </td>
            <td>
                @Html.ActionLink("Edit", "Edit", new { id = item.TrainerID }) |
                @Html.ActionLink("Details", "Details", new { id = item.TrainerID }) |
                @Html.ActionLink("Delete", "Delete", new { id = item.TrainerID })
            </td>
        </tr>
    }

</table>
<br />
Page @(Model.PageCount < Model.PageNumber ? 0 : Model.PageNumber) of @Model.PageCount

@Html.PagedListPager(Model, page => Url.Action("Index",
    new { page, sortOrder = ViewBag.CurrentSort, currentFilter = ViewBag.CurrentFilter })) 